### ISSUE TITLE
How to present a new paragraph in About Me section?

### ISSUE THREAD

**Issue by XinwenCheng** [claudiabdm/cvfy#12]
Hi Claudia,

How to present a new paragraph in the About Me section? The second paragraph in text editor will be shown at the end of the last sentence of the first paragraph in the preview area, seems preview only supports one paragraph.

**Comment by XinwenCheng** [comment]
![image](https://user-images.githubusercontent.com/795334/201509929-cab85b7f-c7b6-4ce5-a191-12bcae36edc2.png)

**Comment by claudiabdm** [comment]
Thanks for reporting it, it's should be possible now!
