### ISSUE TITLE
Upload Profile Picture

### ISSUE THREAD

**Issue by sebbZA** [claudiabdm/cvfy#23]
Hi, 

thank you for this tool and hard work you put in! Im loving it!! More of an suggestion than an issue but have you considered adding an upload profile pic option? It would be great to include an little profile picture in a circle on the top left :)

What do you think?

**Comment by claudiabdm** [comment]
Hi!

I didn't consider it as I am not a huge fan of CVs with photos (and was unnecessary for me) but I'll think about it. 

Thanks

**Comment by sebbZA** [comment]
Thank you for your consideration. Perhaps it could be an optional field. Would make it awesome I think ;).. Thanks again.

**Comment by claudiabdm** [comment]
Fixed by #35
