### ISSUE TITLE
external link issue

### ISSUE THREAD

**Issue by tiwentichat** [claudiabdm/cvfy#49]
when adding website info, it would be cvfy.xyz/example.com, rather than example.com

we may add code like this in pages/index.vue, from line 9::

```
const isExternalLink = !route.path.startsWith('/');

let href;

if (isExternalLink) {

  href = route.path;
} else {

  href = `https://cvfy.xyz${route.path}`;
}
```

and in data/example-cv-settings.ts

change the line 18 from

 website: 'www.MsKnope.com',

to 

website: 'https://www.MsKnope.com',

then, the pdf preview would be https://www.MsKnope.com, rather than cvfy.xyz/msknope.com,

and:

Thank you so much, Claudia, for your great work!

I  really love it！

**Comment by claudiabdm** [comment]
Thank you for reporting this! I’ll check it.
