### ISSUE TITLE
Timezone offset causes incorrect dates in entry fields

### ISSUE THREAD

**Issue by Maheshivara** [claudiabdm/cvfy#59]
# Issue Description:
The date displayed on the site from the form data is off by one day.

# Steps to Reproduce:
1. Set the date of an `Experience` (or `Project`) field to `01/01/2024`.
2. Note the date displayed on the CV.

## Expected Behavior:
The date displayed must match the date entered (`jan 2024`). 

## Actual Behavior:
The date displayed is one day before the date entered (`dec 2023`).

# Images:
- Inserted Date
![inserted date](https://github.com/claudiabdm/cvfy/assets/70645539/948ab7f9-3264-44f6-8dba-58f7533cb0b1)
- Displayed Date
![displayed date](https://github.com/claudiabdm/cvfy/assets/70645539/5a987cc0-c3c6-4e78-9817-00305c9da19e)

**Comment by claudiabdm** [comment]
Thank you for reporting!

I did a quick check on my phone (iOS Safari) and it seems to work fine. I’ll check later in other browsers. What browser/decive are you using?

**Comment by Maheshivara** [comment]
> Thank you for reporting!
> 
> I did a quick check on my phone (iOS Safari) and it seems to work fine. I’ll check later in other browsers. What browser/decive are you using?

I am using `Vivaldi 6.7.3329.41 (Stable channel) (64 bits) on Windows 11`

Also tried Firefox but I had the same problem (as you can see in the image below), a detail is that I'm from Brazil so the timezone here is UTC-3.

![image](https://github.com/claudiabdm/cvfy/assets/70645539/c1ae83ef-9f98-4e24-9f97-8cb2fe2f046d)

Another thing is that if I change to day 2 it displays perfectly which led me to believe that it is a problem with the timezone.

**Comment by Maheshivara** [comment]
A quick test by modifying my computer's timezone showed that any negative timezone relative to UTC presents this problem, while the positive timezones (and UTC itself) are correct.
