### ISSUE TITLE
Let us be able to change headers

### ISSUE THREAD

**Issue by Spontini** [claudiabdm/cvfy#64]
I know adding more languages can be tricky, so Instead of that why not let us edit headers so we can actually create CV's in any language we want. Also for language level section in CV, adding CEFR Levels can be beneficial.

**Comment by claudiabdm** [comment]
Thank you for raising your concerns!

While I understand your point, I don't think editing headers would be a good idea as one of the main points of CvFy is to make the process faster and smoother. Manually editing the headers is the opposite of that in my opinion. Also, adding more languages is not a major concern right now but I'll think of other ways of easing the translation process. 

I'll also consider adding CEFR Levels and how it would work as not every country/language uses this standard.
