### ISSUE TITLE
How do you focus only on preview section when printing

### ISSUE THREAD

**Issue by gjvengelen** [claudiabdm/cvfy#8]
Hi @claudiabdm,
I'm using your app to learn Vue and I'm trying to migrate it to Vue3 and Nuxt3. I'm a long way but I cannot seem to get it to print only the preview section. But looking at your code I cannot find how you make the app focus only on the preview part.

Can you point me in the right direction?

Much appreciated!

**Comment by claudiabdm** [comment]
Hey! I’m sorry you couldn’t find it, this repo needs a bit of refactor 😅 

I’m using a css media query to print only that part, you can check it here: https://github.com/claudiabdm/cvfy/blob/c27777fc9260d5991504a7d7d16599500bc60b02/assets/styles/styles.css

Hope this help!

**Comment by gjvengelen** [comment]
Thnx so much, I completely overlooked it while copy pasting.
That did the trick.
